version: '3.12'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/
    restart: always
    ports: 
    - "2005:2005"

volumes:
  data:
